"""
protocol and performative constants
"""

REGISTER_PROTOCOL = "REGISTER"
CREATE_PROTOCOL = "CREATE"
REQUEST_PROTOCOL = "REQUEST"
QUERY_PROTOCOL = "QUERY"
TRAVEL_PROTOCOL = "INFORM"
RATE_PROTOCOL = "RATE"

REQUEST_PERFORMATIVE = "request"
ACCEPT_PERFORMATIVE = "accept"
REFUSE_PERFORMATIVE = "refuse"
PROPOSE_PERFORMATIVE = "propose"
CANCEL_PERFORMATIVE = "cancel"
INFORM_PERFORMATIVE = "inform"
RATE_PERFORMATIVE = "rate"

